import type { ShapeType } from '@/types'

export const GRID_SIZE = 20

export const DEFAULT_NODE_STYLE = {
  backgroundColor: '#ffffff',
  borderColor: '#9ca3af',
  borderWidth: 1,
  borderRadius: 8,
  textColor: '#1f2937',
  fontSize: 14,
  fontWeight: 'normal',
}

export const DEFAULT_EDGE_STYLE = {
  strokeColor: '#6b7280',
  strokeWidth: 1.5,
  strokeDasharray: '',
  animated: false,
}

// Simple categories (non-nested)
export const SHAPE_CATEGORIES = {
  containers: {
    label: 'Containers',
    shapes: [
      'container',
      'swimlane',
      'swimlane-horizontal',
    ] as ShapeType[],
  },
  basic: {
    label: 'Basic Shapes',
    shapes: [
      'rectangle',
      'rounded-rectangle',
      'ellipse',
      'circle',
      'diamond',
      'triangle',
      'pentagon',
      'hexagon',
      'octagon',
      'star',
      'parallelogram',
      'trapezoid',
      'cylinder',
      'arrow',
      'double-arrow',
      'cloud',
      'callout',
      'note',
      'text',
      'table',
    ] as ShapeType[],
  },
  flowchart: {
    label: 'Flowchart',
    shapes: [
      'terminator',
      'process',
      'decision',
      'data',
      'document',
      'multi-document',
      'predefined-process',
      'manual-input',
      'preparation',
      'database',
      'delay',
      'merge',
      'or',
      'summing-junction',
    ] as ShapeType[],
  },
  uml: {
    label: 'UML',
    shapes: [
      'uml-class',
      'uml-interface',
      'uml-actor',
      'uml-usecase',
      'uml-component',
      'uml-package',
      'uml-state',
      'uml-note',
    ] as ShapeType[],
  },
  network: {
    label: 'Network',
    shapes: [
      'server',
      'database',
      'router',
      'switch',
      'firewall',
      'load-balancer',
      'user',
      'users',
      'laptop',
      'mobile',
      'internet',
    ] as ShapeType[],
  },
  generic: {
    label: 'Generic Cloud',
    shapes: [
      'kubernetes',
      'docker',
      'generic-api',
      'generic-database',
      'generic-cache',
      'generic-queue',
      'generic-load-balancer',
      'generic-cdn',
    ] as ShapeType[],
  },
  office: {
    label: 'Microsoft Office',
    shapes: [
      'office-word',
      'office-excel',
      'office-powerpoint',
      'office-outlook',
      'office-teams',
      'office-onedrive',
      'office-sharepoint',
      'office-onenote',
      'office-access',
      'office-publisher',
      'office-visio',
      'office-project',
    ] as ShapeType[],
  },
  m365: {
    label: 'Microsoft 365',
    shapes: [
      'm365',
      'm365-copilot',
      'm365-planner',
      'm365-todo',
      'm365-forms',
      'm365-stream',
      'm365-whiteboard',
      'm365-lists',
      'm365-loop',
      'm365-bookings',
      'm365-viva-engage',
      'm365-defender',
      'm365-intune',
      'm365-exchange',
    ] as ShapeType[],
  },
  powerPlatform: {
    label: 'Power Platform',
    shapes: [
      'power-bi',
      'power-apps',
      'power-automate',
      'power-virtual-agents',
      'dynamics-365',
    ] as ShapeType[],
  },
}

// Cloud provider categories with nested subcategories
// NOTE: Only includes icons that have actual components in cloudIconComponents registry
export const CLOUD_PROVIDER_CATEGORIES = {
  aws: {
    label: 'Amazon Web Services',
    icon: 'aws',
    subcategories: {
      'aws-core': {
        label: 'Core Services',
        shapes: [
          'aws-ec2',
          'aws-lambda',
          'aws-s3',
          'aws-rds',
          'aws-dynamodb',
          'aws-ecs',
          'aws-eks',
        ] as ShapeType[],
      },
      'aws-networking': {
        label: 'Networking',
        shapes: [
          'aws-vpc',
          'aws-cloudfront',
          'aws-route53',
          'aws-api-gateway',
        ] as ShapeType[],
      },
      'aws-integration': {
        label: 'Integration',
        shapes: [
          'aws-sns',
          'aws-sqs',
          'aws-iam',
        ] as ShapeType[],
      },
    },
  },
  azure: {
    label: 'Microsoft Azure',
    icon: 'azure',
    subcategories: {
      'azure-core': {
        label: 'Core Services',
        shapes: [
          'azure-vm',
          'azure-functions',
          'azure-app-service',
          'azure-storage',
          'azure-sql',
          'azure-cosmos',
          'azure-aks',
        ] as ShapeType[],
      },
    },
  },
  gcp: {
    label: 'Google Cloud',
    icon: 'gcp',
    subcategories: {
      'gcp-core': {
        label: 'Core Services',
        shapes: [
          'gcp-compute',
          'gcp-functions',
          'gcp-app-engine',
          'gcp-cloud-run',
          'gcp-gke',
          'gcp-storage',
        ] as ShapeType[],
      },
      'gcp-database': {
        label: 'Databases',
        shapes: [
          'gcp-cloud-sql',
          'gcp-firestore',
          'gcp-bigtable',
          'gcp-spanner',
        ] as ShapeType[],
      },
      'gcp-networking': {
        label: 'Networking',
        shapes: [
          'gcp-vpc',
          'gcp-load-balancing',
          'gcp-cloud-cdn',
          'gcp-iam',
        ] as ShapeType[],
      },
      'gcp-analytics': {
        label: 'Analytics',
        shapes: [
          'gcp-bigquery',
          'gcp-pubsub',
        ] as ShapeType[],
      },
    },
  },
}

export const SHAPE_LABELS: Record<ShapeType, string> = {
  // Custom shapes
  'custom-shape': 'Custom Shape',
  // Web images
  'web-image': 'Web Image',
  // Containers and Swimlanes
  container: 'Container',
  swimlane: 'Swimlane',
  'swimlane-horizontal': 'Swimlane (Horizontal)',
  // Basic shapes
  rectangle: 'Rectangle',
  'rounded-rectangle': 'Rounded Rectangle',
  ellipse: 'Ellipse',
  circle: 'Circle',
  diamond: 'Diamond',
  parallelogram: 'Parallelogram',
  trapezoid: 'Trapezoid',
  cylinder: 'Cylinder',
  triangle: 'Triangle',
  pentagon: 'Pentagon',
  hexagon: 'Hexagon',
  octagon: 'Octagon',
  star: 'Star',
  arrow: 'Arrow',
  'double-arrow': 'Double Arrow',
  cloud: 'Cloud',
  callout: 'Callout',
  note: 'Note',
  text: 'Text',
  table: 'Table',
  junction: 'Junction',
  // Flowchart shapes
  process: 'Process',
  decision: 'Decision',
  terminator: 'Start/End',
  data: 'Data',
  document: 'Document',
  'multi-document': 'Multi-Document',
  'predefined-process': 'Predefined Process',
  'manual-input': 'Manual Input',
  preparation: 'Preparation',
  delay: 'Delay',
  database: 'Database',
  merge: 'Merge',
  or: 'Or',
  'summing-junction': 'Summing Junction',
  // UML shapes
  'uml-class': 'Class',
  'uml-interface': 'Interface',
  'uml-actor': 'Actor',
  'uml-usecase': 'Use Case',
  'uml-component': 'Component',
  'uml-package': 'Package',
  'uml-state': 'State',
  'uml-note': 'Note',
  // Network shapes
  server: 'Server',
  router: 'Router',
  switch: 'Switch',
  firewall: 'Firewall',
  'load-balancer': 'Load Balancer',
  user: 'User',
  users: 'Users',
  laptop: 'Laptop',
  mobile: 'Mobile',
  internet: 'Internet',
  // AWS Compute
  'aws-ec2': 'EC2',
  'aws-lambda': 'Lambda',
  'aws-elastic-beanstalk': 'Elastic Beanstalk',
  'aws-lightsail': 'Lightsail',
  'aws-outposts': 'Outposts',
  'aws-wavelength': 'Wavelength',
  'aws-local-zones': 'Local Zones',
  'aws-batch': 'Batch',
  // AWS Containers
  'aws-ecs': 'ECS',
  'aws-eks': 'EKS',
  'aws-fargate': 'Fargate',
  'aws-ecr': 'ECR',
  'aws-app-runner': 'App Runner',
  // AWS Storage
  'aws-s3': 'S3',
  'aws-ebs': 'EBS',
  'aws-efs': 'EFS',
  'aws-fsx': 'FSx',
  'aws-storage-gateway': 'Storage Gateway',
  'aws-backup': 'Backup',
  'aws-snow-family': 'Snow Family',
  // AWS Database
  'aws-rds': 'RDS',
  'aws-dynamodb': 'DynamoDB',
  'aws-elasticache': 'ElastiCache',
  'aws-redshift': 'Redshift',
  'aws-neptune': 'Neptune',
  'aws-documentdb': 'DocumentDB',
  'aws-qldb': 'QLDB',
  'aws-timestream': 'Timestream',
  'aws-memorydb': 'MemoryDB',
  'aws-keyspaces': 'Keyspaces',
  // AWS Networking
  'aws-vpc': 'VPC',
  'aws-cloudfront': 'CloudFront',
  'aws-route53': 'Route 53',
  'aws-api-gateway': 'API Gateway',
  'aws-direct-connect': 'Direct Connect',
  'aws-global-accelerator': 'Global Accelerator',
  'aws-transit-gateway': 'Transit Gateway',
  'aws-privatelink': 'PrivateLink',
  'aws-elb': 'ELB',
  // AWS Security
  'aws-iam': 'IAM',
  'aws-cognito': 'Cognito',
  'aws-secrets-manager': 'Secrets Manager',
  'aws-kms': 'KMS',
  'aws-waf': 'WAF',
  'aws-shield': 'Shield',
  'aws-guardduty': 'GuardDuty',
  'aws-inspector': 'Inspector',
  'aws-macie': 'Macie',
  'aws-security-hub': 'Security Hub',
  // AWS Analytics
  'aws-kinesis': 'Kinesis',
  'aws-athena': 'Athena',
  'aws-emr': 'EMR',
  'aws-glue': 'Glue',
  'aws-lake-formation': 'Lake Formation',
  'aws-quicksight': 'QuickSight',
  'aws-data-pipeline': 'Data Pipeline',
  'aws-msk': 'MSK',
  'aws-opensearch': 'OpenSearch',
  // AWS ML/AI
  'aws-sagemaker': 'SageMaker',
  'aws-rekognition': 'Rekognition',
  'aws-comprehend': 'Comprehend',
  'aws-lex': 'Lex',
  'aws-polly': 'Polly',
  'aws-transcribe': 'Transcribe',
  'aws-translate': 'Translate',
  'aws-textract': 'Textract',
  'aws-bedrock': 'Bedrock',
  // AWS Integration
  'aws-sns': 'SNS',
  'aws-sqs': 'SQS',
  'aws-eventbridge': 'EventBridge',
  'aws-step-functions': 'Step Functions',
  'aws-appsync': 'AppSync',
  'aws-mq': 'MQ',
  'aws-app-mesh': 'App Mesh',
  // AWS Developer
  'aws-codecommit': 'CodeCommit',
  'aws-codebuild': 'CodeBuild',
  'aws-codedeploy': 'CodeDeploy',
  'aws-codepipeline': 'CodePipeline',
  'aws-cloud9': 'Cloud9',
  'aws-xray': 'X-Ray',
  'aws-cloudshell': 'CloudShell',
  // AWS Management
  'aws-cloudwatch': 'CloudWatch',
  'aws-cloudtrail': 'CloudTrail',
  'aws-config': 'Config',
  'aws-systems-manager': 'Systems Manager',
  'aws-cloudformation': 'CloudFormation',
  'aws-service-catalog': 'Service Catalog',
  'aws-trusted-advisor': 'Trusted Advisor',
  'aws-organizations': 'Organizations',
  'aws-control-tower': 'Control Tower',
  'aws-amplify': 'Amplify',
  // Azure Cloud icons - Core
  'azure-vm': 'Virtual Machine',
  'azure-storage': 'Storage Account',
  'azure-functions': 'Functions',
  'azure-sql': 'SQL Database',
  'azure-cosmos': 'Cosmos DB',
  'azure-app-service': 'App Service',
  'azure-aks': 'AKS',
  'azure-cdn': 'CDN',
  'azure-vnet': 'Virtual Network',
  'azure-keyvault': 'Key Vault',
  'azure-event-hub': 'Event Hubs',
  'azure-service-bus': 'Service Bus',
  'azure-logic-apps': 'Logic Apps',
  'azure-databricks': 'Databricks',
  'azure-active-directory': 'Active Directory',
  'azure-container-registry': 'Container Registry',
  'azure-redis-cache': 'Redis Cache',
  'azure-app-gateway': 'App Gateway',
  'azure-front-door': 'Front Door',
  'azure-monitor': 'Monitor',
  // Azure - Analytics
  'azure-synapse': 'Synapse Analytics',
  'azure-data-factory': 'Data Factory',
  'azure-stream-analytics': 'Stream Analytics',
  'azure-hdinsight': 'HDInsight',
  'azure-data-lake': 'Data Lake',
  'azure-analysis-services': 'Analysis Services',
  'azure-log-analytics': 'Log Analytics',
  'azure-purview': 'Purview',
  // Azure - Compute
  'azure-vm-scale-sets': 'VM Scale Sets',
  'azure-batch': 'Batch',
  'azure-cloud-services': 'Cloud Services',
  'azure-service-fabric': 'Service Fabric',
  // Azure - Containers
  'azure-container-instances': 'Container Instances',
  'azure-container-apps': 'Container Apps',
  // Azure - Databases
  'azure-mysql': 'MySQL',
  'azure-postgresql': 'PostgreSQL',
  'azure-mariadb': 'MariaDB',
  'azure-sql-managed-instance': 'SQL Managed Instance',
  'azure-table-storage': 'Table Storage',
  // Azure - Networking
  'azure-load-balancer': 'Load Balancer',
  'azure-vpn-gateway': 'VPN Gateway',
  'azure-expressroute': 'ExpressRoute',
  'azure-traffic-manager': 'Traffic Manager',
  'azure-dns': 'DNS',
  'azure-private-link': 'Private Link',
  'azure-bastion': 'Bastion',
  'azure-nat-gateway': 'NAT Gateway',
  // Azure - Security
  'azure-security-center': 'Security Center',
  'azure-sentinel': 'Sentinel',
  'azure-ddos-protection': 'DDoS Protection',
  'azure-firewall': 'Firewall',
  'azure-defender': 'Defender',
  // Azure - AI + ML
  'azure-cognitive-services': 'Cognitive Services',
  'azure-machine-learning': 'Machine Learning',
  'azure-bot-service': 'Bot Service',
  'azure-openai': 'Azure OpenAI',
  // Azure - Integration
  'azure-api-management': 'API Management',
  'azure-event-grid': 'Event Grid',
  // Azure - Storage
  'azure-blob-storage': 'Blob Storage',
  'azure-file-storage': 'File Storage',
  'azure-queue-storage': 'Queue Storage',
  'azure-data-lake-storage': 'Data Lake Storage',
  'azure-netapp-files': 'NetApp Files',
  // Azure - Identity
  'azure-b2c': 'Azure AD B2C',
  'azure-managed-identities': 'Managed Identities',
  'azure-entra-id': 'Entra ID',
  // Azure - DevOps
  'azure-devops': 'Azure DevOps',
  'azure-repos': 'Repos',
  'azure-pipelines': 'Pipelines',
  'azure-boards': 'Boards',
  'azure-test-plans': 'Test Plans',
  'azure-artifacts': 'Artifacts',
  // Azure - Web
  'azure-static-web-apps': 'Static Web Apps',
  'azure-signalr': 'SignalR',
  'azure-notification-hubs': 'Notification Hubs',
  // GCP Compute
  'gcp-compute': 'Compute Engine',
  'gcp-functions': 'Cloud Functions',
  'gcp-app-engine': 'App Engine',
  'gcp-cloud-run': 'Cloud Run',
  'gcp-gke': 'GKE',
  // GCP Storage
  'gcp-storage': 'Cloud Storage',
  'gcp-persistent-disk': 'Persistent Disk',
  'gcp-filestore': 'Filestore',
  'gcp-storage-transfer': 'Storage Transfer',
  // GCP Database
  'gcp-cloud-sql': 'Cloud SQL',
  'gcp-firestore': 'Firestore',
  'gcp-bigtable': 'Bigtable',
  'gcp-spanner': 'Spanner',
  'gcp-memorystore': 'Memorystore',
  'gcp-alloydb': 'AlloyDB',
  // GCP Networking
  'gcp-vpc': 'VPC',
  'gcp-load-balancing': 'Load Balancing',
  'gcp-cloud-cdn': 'Cloud CDN',
  'gcp-cloud-dns': 'Cloud DNS',
  'gcp-cloud-nat': 'Cloud NAT',
  'gcp-cloud-armor': 'Cloud Armor',
  'gcp-cloud-interconnect': 'Cloud Interconnect',
  'gcp-network-connectivity': 'Network Connectivity',
  // GCP Security
  'gcp-iam': 'Cloud IAM',
  'gcp-cloud-kms': 'Cloud KMS',
  'gcp-secret-manager': 'Secret Manager',
  'gcp-security-command-center': 'Security Command Center',
  'gcp-beyondcorp': 'BeyondCorp',
  'gcp-certificate-manager': 'Certificate Manager',
  // GCP Analytics
  'gcp-bigquery': 'BigQuery',
  'gcp-dataflow': 'Dataflow',
  'gcp-dataproc': 'Dataproc',
  'gcp-pubsub': 'Pub/Sub',
  'gcp-data-fusion': 'Data Fusion',
  'gcp-looker': 'Looker',
  'gcp-dataform': 'Dataform',
  // GCP AI/ML
  'gcp-vertex-ai': 'Vertex AI',
  'gcp-vision-ai': 'Vision AI',
  'gcp-natural-language': 'Natural Language',
  'gcp-speech-to-text': 'Speech-to-Text',
  'gcp-translation': 'Translation',
  'gcp-document-ai': 'Document AI',
  'gcp-recommendations-ai': 'Recommendations AI',
  'gcp-automl': 'AutoML',
  // GCP Developer
  'gcp-cloud-build': 'Cloud Build',
  'gcp-artifact-registry': 'Artifact Registry',
  'gcp-cloud-source-repos': 'Cloud Source Repos',
  'gcp-cloud-deploy': 'Cloud Deploy',
  'gcp-cloud-workstations': 'Cloud Workstations',
  // GCP Management
  'gcp-cloud-monitoring': 'Cloud Monitoring',
  'gcp-cloud-logging': 'Cloud Logging',
  'gcp-cloud-trace': 'Cloud Trace',
  'gcp-error-reporting': 'Error Reporting',
  'gcp-cloud-debugger': 'Cloud Debugger',
  'gcp-cloud-profiler': 'Cloud Profiler',
  // GCP Integration
  'gcp-cloud-tasks': 'Cloud Tasks',
  'gcp-cloud-scheduler': 'Cloud Scheduler',
  'gcp-workflows': 'Workflows',
  'gcp-eventarc': 'Eventarc',
  'gcp-api-gateway': 'API Gateway',
  // Generic Cloud/DevOps
  'kubernetes': 'Kubernetes',
  'docker': 'Docker',
  'generic-api': 'API',
  'generic-database': 'Database',
  'generic-cache': 'Cache',
  'generic-queue': 'Queue',
  'generic-load-balancer': 'Load Balancer',
  'generic-cdn': 'CDN',
  // Microsoft Office
  'office-word': 'Word',
  'office-excel': 'Excel',
  'office-powerpoint': 'PowerPoint',
  'office-outlook': 'Outlook',
  'office-teams': 'Teams',
  'office-onedrive': 'OneDrive',
  'office-sharepoint': 'SharePoint',
  'office-onenote': 'OneNote',
  'office-access': 'Access',
  'office-publisher': 'Publisher',
  'office-visio': 'Visio',
  'office-project': 'Project',
  // Microsoft 365
  'm365': 'Microsoft 365',
  'm365-copilot': 'Copilot',
  'm365-planner': 'Planner',
  'm365-todo': 'To Do',
  'm365-forms': 'Forms',
  'm365-stream': 'Stream',
  'm365-whiteboard': 'Whiteboard',
  'm365-lists': 'Lists',
  'm365-loop': 'Loop',
  'm365-bookings': 'Bookings',
  'm365-viva-engage': 'Viva Engage',
  'm365-defender': 'Defender',
  'm365-intune': 'Intune',
  'm365-exchange': 'Exchange',
  // Power Platform
  'power-bi': 'Power BI',
  'power-apps': 'Power Apps',
  'power-automate': 'Power Automate',
  'power-virtual-agents': 'Power Virtual Agents',
  'dynamics-365': 'Dynamics 365',
}

export const KEYBOARD_SHORTCUTS = {
  delete: ['Delete', 'Backspace'],
  copy: ['Control+c', 'Meta+c'],
  paste: ['Control+v', 'Meta+v'],
  cut: ['Control+x', 'Meta+x'],
  undo: ['Control+z', 'Meta+z'],
  redo: ['Control+Shift+z', 'Meta+Shift+z', 'Control+y', 'Meta+y'],
  selectAll: ['Control+a', 'Meta+a'],
  save: ['Control+s', 'Meta+s'],
  zoomIn: ['Control+=', 'Meta+='],
  zoomOut: ['Control+-', 'Meta+-'],
  zoomReset: ['Control+0', 'Meta+0'],
  toggleGrid: ['Control+g', 'Meta+g'],
}

export const AUTO_SAVE_INTERVAL = 30000 // 30 seconds

export const MAX_HISTORY_LENGTH = 50
