import type { ShapeType } from '@/types'

export const GRID_SIZE = 20

export const DEFAULT_NODE_STYLE = {
  backgroundColor: '#ffffff',
  borderColor: '#9ca3af',
  borderWidth: 1,
  borderRadius: 8,
  textColor: '#1f2937',
  fontSize: 14,
  fontWeight: 'normal',
}

export const DEFAULT_EDGE_STYLE = {
  strokeColor: '#6b7280',
  strokeWidth: 1.5,
  strokeDasharray: '',
  animated: false,
}

export const SHAPE_CATEGORIES = {
  basic: {
    label: 'Basic Shapes',
    shapes: [
      'rectangle',
      'rounded-rectangle',
      'ellipse',
      'circle',
      'diamond',
      'triangle',
      'pentagon',
      'hexagon',
      'octagon',
      'star',
      'parallelogram',
      'trapezoid',
      'cylinder',
      'arrow',
      'double-arrow',
      'cloud',
      'callout',
      'note',
      'text',
    ] as ShapeType[],
  },
  flowchart: {
    label: 'Flowchart',
    shapes: [
      'terminator',
      'process',
      'decision',
      'data',
      'document',
      'multi-document',
      'predefined-process',
      'manual-input',
      'preparation',
      'database',
      'delay',
      'merge',
      'or',
      'summing-junction',
    ] as ShapeType[],
  },
  uml: {
    label: 'UML',
    shapes: [
      'uml-class',
      'uml-interface',
      'uml-actor',
      'uml-usecase',
      'uml-component',
      'uml-package',
      'uml-state',
      'uml-note',
    ] as ShapeType[],
  },
  network: {
    label: 'Network',
    shapes: [
      'server',
      'database',
      'router',
      'switch',
      'firewall',
      'load-balancer',
      'user',
      'users',
      'laptop',
      'mobile',
      'internet',
    ] as ShapeType[],
  },
  aws: {
    label: 'AWS',
    shapes: [
      'aws-ec2',
      'aws-s3',
      'aws-lambda',
      'aws-rds',
      'aws-dynamodb',
      'aws-api-gateway',
      'aws-sns',
      'aws-sqs',
      'aws-cloudfront',
      'aws-route53',
      'aws-vpc',
      'aws-iam',
      'aws-ecs',
      'aws-eks',
      'aws-cognito',
      'aws-step-functions',
      'aws-kinesis',
      'aws-redshift',
      'aws-elasticache',
      'aws-cloudwatch',
      'aws-secrets-manager',
      'aws-eventbridge',
      'aws-amplify',
      'aws-appsync',
    ] as ShapeType[],
  },
  azure: {
    label: 'Azure',
    shapes: [
      'azure-vm',
      'azure-storage',
      'azure-functions',
      'azure-sql',
      'azure-cosmos',
      'azure-app-service',
      'azure-aks',
      'azure-cdn',
      'azure-vnet',
      'azure-keyvault',
      'azure-event-hub',
      'azure-service-bus',
      'azure-logic-apps',
      'azure-databricks',
      'azure-active-directory',
      'azure-container-registry',
      'azure-redis-cache',
      'azure-app-gateway',
      'azure-front-door',
      'azure-monitor',
    ] as ShapeType[],
  },
  gcp: {
    label: 'GCP',
    shapes: [
      'gcp-compute',
      'gcp-storage',
      'gcp-functions',
      'gcp-bigquery',
      'gcp-pubsub',
      'gcp-gke',
      'gcp-cloud-run',
      'gcp-firestore',
      'gcp-cloud-sql',
      'gcp-spanner',
      'gcp-dataflow',
      'gcp-cloud-armor',
      'gcp-cloud-build',
      'gcp-artifact-registry',
      'gcp-secret-manager',
    ] as ShapeType[],
  },
  generic: {
    label: 'Generic',
    shapes: [
      'kubernetes',
      'docker',
      'generic-api',
      'generic-database',
      'generic-cache',
      'generic-queue',
      'generic-load-balancer',
      'generic-cdn',
    ] as ShapeType[],
  },
}

export const SHAPE_LABELS: Record<ShapeType, string> = {
  // Basic shapes
  rectangle: 'Rectangle',
  'rounded-rectangle': 'Rounded Rectangle',
  ellipse: 'Ellipse',
  circle: 'Circle',
  diamond: 'Diamond',
  parallelogram: 'Parallelogram',
  trapezoid: 'Trapezoid',
  cylinder: 'Cylinder',
  triangle: 'Triangle',
  pentagon: 'Pentagon',
  hexagon: 'Hexagon',
  octagon: 'Octagon',
  star: 'Star',
  arrow: 'Arrow',
  'double-arrow': 'Double Arrow',
  cloud: 'Cloud',
  callout: 'Callout',
  note: 'Note',
  text: 'Text',
  // Flowchart shapes
  process: 'Process',
  decision: 'Decision',
  terminator: 'Start/End',
  data: 'Data',
  document: 'Document',
  'multi-document': 'Multi-Document',
  'predefined-process': 'Predefined Process',
  'manual-input': 'Manual Input',
  preparation: 'Preparation',
  delay: 'Delay',
  database: 'Database',
  merge: 'Merge',
  or: 'Or',
  'summing-junction': 'Summing Junction',
  // UML shapes
  'uml-class': 'Class',
  'uml-interface': 'Interface',
  'uml-actor': 'Actor',
  'uml-usecase': 'Use Case',
  'uml-component': 'Component',
  'uml-package': 'Package',
  'uml-state': 'State',
  'uml-note': 'Note',
  // Network shapes
  server: 'Server',
  router: 'Router',
  switch: 'Switch',
  firewall: 'Firewall',
  'load-balancer': 'Load Balancer',
  user: 'User',
  users: 'Users',
  laptop: 'Laptop',
  mobile: 'Mobile',
  internet: 'Internet',
  // AWS Cloud icons
  'aws-ec2': 'EC2',
  'aws-s3': 'S3',
  'aws-lambda': 'Lambda',
  'aws-rds': 'RDS',
  'aws-dynamodb': 'DynamoDB',
  'aws-api-gateway': 'API Gateway',
  'aws-sns': 'SNS',
  'aws-sqs': 'SQS',
  'aws-cloudfront': 'CloudFront',
  'aws-route53': 'Route 53',
  'aws-vpc': 'VPC',
  'aws-iam': 'IAM',
  'aws-ecs': 'ECS',
  'aws-eks': 'EKS',
  'aws-cognito': 'Cognito',
  'aws-step-functions': 'Step Functions',
  'aws-kinesis': 'Kinesis',
  'aws-redshift': 'Redshift',
  'aws-elasticache': 'ElastiCache',
  'aws-cloudwatch': 'CloudWatch',
  'aws-secrets-manager': 'Secrets Manager',
  'aws-eventbridge': 'EventBridge',
  'aws-amplify': 'Amplify',
  'aws-appsync': 'AppSync',
  // Azure Cloud icons
  'azure-vm': 'Virtual Machine',
  'azure-storage': 'Storage',
  'azure-functions': 'Functions',
  'azure-sql': 'SQL Database',
  'azure-cosmos': 'Cosmos DB',
  'azure-app-service': 'App Service',
  'azure-aks': 'AKS',
  'azure-cdn': 'CDN',
  'azure-vnet': 'Virtual Network',
  'azure-keyvault': 'Key Vault',
  'azure-event-hub': 'Event Hub',
  'azure-service-bus': 'Service Bus',
  'azure-logic-apps': 'Logic Apps',
  'azure-databricks': 'Databricks',
  'azure-active-directory': 'Active Directory',
  'azure-container-registry': 'Container Registry',
  'azure-redis-cache': 'Redis Cache',
  'azure-app-gateway': 'App Gateway',
  'azure-front-door': 'Front Door',
  'azure-monitor': 'Monitor',
  // GCP Cloud icons
  'gcp-compute': 'Compute Engine',
  'gcp-storage': 'Cloud Storage',
  'gcp-functions': 'Cloud Functions',
  'gcp-bigquery': 'BigQuery',
  'gcp-pubsub': 'Pub/Sub',
  'gcp-gke': 'GKE',
  'gcp-cloud-run': 'Cloud Run',
  'gcp-firestore': 'Firestore',
  'gcp-cloud-sql': 'Cloud SQL',
  'gcp-spanner': 'Spanner',
  'gcp-dataflow': 'Dataflow',
  'gcp-cloud-armor': 'Cloud Armor',
  'gcp-cloud-build': 'Cloud Build',
  'gcp-artifact-registry': 'Artifact Registry',
  'gcp-secret-manager': 'Secret Manager',
  // Generic Cloud/DevOps
  'kubernetes': 'Kubernetes',
  'docker': 'Docker',
  'generic-api': 'API',
  'generic-database': 'Database',
  'generic-cache': 'Cache',
  'generic-queue': 'Queue',
  'generic-load-balancer': 'Load Balancer',
  'generic-cdn': 'CDN',
}

export const KEYBOARD_SHORTCUTS = {
  delete: ['Delete', 'Backspace'],
  copy: ['Control+c', 'Meta+c'],
  paste: ['Control+v', 'Meta+v'],
  cut: ['Control+x', 'Meta+x'],
  undo: ['Control+z', 'Meta+z'],
  redo: ['Control+Shift+z', 'Meta+Shift+z', 'Control+y', 'Meta+y'],
  selectAll: ['Control+a', 'Meta+a'],
  save: ['Control+s', 'Meta+s'],
  zoomIn: ['Control+=', 'Meta+='],
  zoomOut: ['Control+-', 'Meta+-'],
  zoomReset: ['Control+0', 'Meta+0'],
  toggleGrid: ['Control+g', 'Meta+g'],
}

export const AUTO_SAVE_INTERVAL = 30000 // 30 seconds

export const MAX_HISTORY_LENGTH = 50
